#!/bin/bash

set -euo pipefail
set -x

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
basedir="$DIR/ddo"
bucket=s3://downloads-dlang-org
extraargs="--acl public-read --cache-control max-age=604800"

function awsb2
{
    region=$(aws --profile ddo configure list | awk '$1 == "region" { print $2 }')
    aws --endpoint-url="https://s3.${region}.backblazeb2.com" $@
}

pushd $DIR

# Build everything (just to be sure to be up-to-date)
make
./src/build-gen-index s3_index
./src/build-gen-index generate

# Update the s3 bucket
awsb2 --output json --profile ddo s3 cp   $basedir/index.html    $bucket/index.html    $extraargs
awsb2 --output json --profile ddo s3 sync $basedir/releases/     $bucket/releases/     $extraargs
awsb2 --output json --profile ddo s3 sync $basedir/pre-releases/ $bucket/pre-releases/ $extraargs
awsb2 --output json --profile ddo s3 sync $basedir/other/        $bucket/other/        $extraargs

popd $DIR
